### PR TITLE
Fix some greeting bugs

### LINKED ISSUE #51: [Bug] Mona triggers when usual greeting words are included as parts of other words
image

This is super annoying.

### PR DESCRIPTION
**Pull request by nikitasakau**
Fix #51
- Fixed bug when word includes one of greeting words. (For example: t**hey**). Now bot ignores these words.
- Fixed bug when message includes several greeting words. (For example: `Hello, good morning!`). Now bot responds on such messages only once.

DEMO:
https://youtu.be/ftHMPZf_E98

### CODE REVIEW

**Comment by AleksSenkou** [comment]
Is such a case possible after making changes you propose?

image

**Comment by nikitasakau** [comment]
@AleksSenkou Nope 🙂
ezgif-4-f7dfeeba9da7

**Review by AleksSenkou — APPROVED** [review]
NICE

File: scripts/communication.js [hunk 1]
```diff
@@ -30,9 +30,10 @@ const responsesOnGreeting = [
 ];
 
 const handlerCommunication = (robot, queries, answers) => {
-  queries.forEach((query) => {
-    robot.hear(new RegExp(query, 'i'), response => response.send(response.random(answers)));
-  });
+  const matchKeys = queries.join('|');
+  const regexp = new RegExp(`\\b(${matchKeys})\\b`, 'i');
```
Comment (ezhlobo) [inline scripts/communication.js]: It doesn't look like we have tests for this file so it's hard to say, but I'm quite cautious that it might not work when we handle what Mona says:

https://github.com/datarockets/mona/blob/7d3d887a233afd06ef51e5dc416b9bfc5342f0dd/scripts/communication.js#L40

Also from the demo it's not clear how it handles regexp items (we might consider to convert them into plain string this case):
https://github.com/datarockets/mona/blob/7d3d887a233afd06ef51e5dc416b9bfc5342f0dd/scripts/communication.js#L10

Comment (nikitasakau) [reply scripts/communication.js]: @ezhlobo Good point 👍 Thanks. New demo:

new-demo

**Comment by nikitasakau** [comment]
FYI: I am going to merge this pull request soon. If somebody has comments - let me know and I can fix it in separate PR 😉
